title: jingsam's blog
url: http://your-site.com

date_format: "%Y-%m-%d"
time_format: "%H:%M"

# Default extension for new posts and pages
post_ext: md
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: theme:post
page_layout: theme:page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft