# Settings for main header
title: jingsam's blog
subtitle: A geospatial hacker

# Links for main navigation
main_nav:
  - { url: '/', title: '首页' }
  - { url: '/archive/', title: '归档' }
  - { url: '/feed/', title: '订阅' }

# Link labels
permalink_label: "文章链接"
read_more_label: "继续阅读 →"

# Show excerpts on post index
excerpt_posts: true
# Excerpt linkposts on index
excerpt_linkposts: false

search: google

sharing:
  - facebook
  - twitter
  - gplus
  - email

# Defaults to sharing with links (for speed and privacy)
# To use javascript share buttons, set share_with: buttons
share_with: links

# Embed comments, options: false, facebook, disqus
comments: disqus

# Center the text in post and page headings.
center_headings: true
